# Property's Sale Price Prediction Using Linear Regression
Dataset: https://www.kaggle.com/competitions/house-prices-advanced-regression-techniques/data?select=train.csv

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
from sklearn import datasets, linear_model, metrics

In [4]:
df = pd.read_csv('C:/Users/rosyi/Videos/Machine Learning/Day 13. Supervised Learning - Linear Regression/train.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

#### Cleansing Data

In [5]:
df.columns

Index(['Id', 'MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'Alley', 'LotShape', 'LandContour', 'Utilities', 'LotConfig',
       'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType',
       'HouseStyle', 'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd',
       'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType',
       'MasVnrArea', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1',
       'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating',
       'HeatingQC', 'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual',
       'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'PoolQC',
       'Fence', 'MiscFeature', 'MiscVal', 'MoSold', 'YrSold', 'SaleType',
       'SaleCondition', 'SalePrice'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

Terdapat beberapa column yang memiliki nilai Nan, hal yang perlu dilakukan adalah dengan menghilangkan column dengan jumlah Nan lebih dari 50% dan menggunakan nilai mean/nedian untuk column yang memiliki jumlah Nan yang kurang dari 50%

In [7]:
# Menghilangkan column yang memiliki Nan lebih dari 50%
df.drop(['Alley', 'FireplaceQu', 'PoolQC', 'Fence', 'MiscFeature'], axis = 'columns', inplace=True)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 76 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     1452 non-null   object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  GarageType     1379 non-null   object
 57  GarageYrBlt    1379 non-null   float64
 58  GarageFinish   1379 non-null   object
 59  GarageCars     1460 non-null   int64
 60  GarageArea     1460 non-null   int64
 61  GarageQual     1379 non-null   object
 62  GarageCond     1379 non-null   object
 63  PavedDrive     1460 non-null   object
 64  WoodDeckSF     1460 non-null   int64
 65  OpenPorchSF    1460 non-null   int64
 66  EnclosedPorch  1460 non-null   int64
 67  3SsnPorch      1460 non-null   int64
 68  ScreenPorch    1460 non-null   int64
 69  PoolArea       1460 non-null   int64
 70  MiscVal        1460 non-null   int64
 71  MoSold         1460 non-null   int64
 72  YrSold         1460 non-null   int64
 73  SaleType       1460 non-null   object
 74  SaleCondition  1460 non-null   object
 75  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(38)
memory usage: 867.0+ KB

In [9]:
# Mengisi column numerikal yang memiliki Nan dengan median
df[['LotFrontage','MasVnrArea', 'GarageYrBlt']] = df[['LotFrontage','MasVnrArea', 'GarageYrBlt']].fillna(df[['LotFrontage','MasVnrArea', 'GarageYrBlt']].median()) 

# Mengisi column categorical dengan modus.
df[['MasVnrType','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']] = df[['MasVnrType','BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond']].apply(lambda x: x.fillna(x.value_counts().index[0]))

In [10]:
from pandas import isnull

np.where(df == isnull)

# Data sudah tidak memiliki nilai NaN yang berarti sudah clean dan siap untuk digunakan ke tahap selanjutnya.

(array([], dtype=int64), array([], dtype=int64))

#### One-Hot Encoding

In [11]:
OHD = pd.get_dummies(df, columns = ['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual', 'Functional', 'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PavedDrive', 'SaleType','SaleCondition'])
OHD

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,62.0,7917,6,5,1999,2000,0.0,0,...,0,0,0,1,0,0,0,0,1,0
1456,1457,20,85.0,13175,6,6,1978,1988,119.0,790,...,0,0,0,1,0,0,0,0,1,0
1457,1458,70,66.0,9042,7,9,1941,2006,0.0,275,...,0,0,0,1,0,0,0,0,1,0
1458,1459,20,68.0,9717,5,6,1950,1996,0.0,49,...,0,0,0,1,0,0,0,0,1,0
1459,1460,20,75.0,9937,5,6,1965,1965,0.0,830,...,0,0,0,1,0,0,0,0,1,0

#### Create X and Y variable for training and testing

In [12]:
X = OHD.loc[:, OHD.columns != 'SalePrice']
y = OHD['SalePrice']

#### Splitting X and y into training and testing sets

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4,
                                                    random_state=1)

#### Train Linear Regression with X_train and y_train

In [14]:
from sklearn.linear_model import LinearRegression

# create linear regression object
reg = linear_model.LinearRegression()
 
# train the model using the training sets
reg.fit(X_train, y_train)
 
# regression coefficients
print('Coefficients: ', reg.coef_)

# regression intercept
print('Intercept: ', reg.intercept_)

Coefficients:  [ 2.80083267e+00 -1.57396024e+02  5.13663610e+01  1.08310570e+00
  4.88790458e+03  6.07457676e+03  2.39259088e+02  3.33935675e+01
  1.48043563e+01  1.91606866e+01  1.02564681e+00 -3.01253820e+00
  1.71738282e+01  1.74963307e+01  2.64050267e+01 -6.25099895e+00
  3.76503488e+01 -7.29837917e+02  1.30130930e+03  3.73953137e+03
  1.87301635e+03 -1.73578156e+03 -1.17061033e+04 -9.18486652e+01
  2.56138195e+03  2.32370643e+01  4.43011323e+03  1.29127168e+01
  6.37790424e+00  2.57693421e+01 -3.56895758e+00  1.94948445e+01
  1.66634377e+01  4.03498298e+01  6.58252162e-01 -2.96096559e+02
 -7.15920701e+02 -3.68863480e+04  1.76955975e+04  1.74019435e+04
  8.40114440e+02  9.48692566e+02  1.47002986e+03 -1.47002986e+03
  2.59411114e+03  1.28083660e+03 -7.32873844e+03  3.45379070e+03
  1.84008245e+02  1.13466687e+04 -1.64317525e+04  4.90107554e+03
  2.45846356e+04 -2.45846356e+04  2.06511350e+03  7.06481354e+03
 -5.60361045e+02 -7.59034460e+03 -9.79221396e+02  2.53135656e+04
  2.66478072e+04 -5.19613728e+04  1.92914957e+04  8.58700552e+03
  9.20815515e+03 -6.44164120e+03 -9.69037064e+03 -5.06480524e+03
  1.79872163e+04 -1.67523933e+04 -1.32520870e+04 -1.12014383e+04
  5.18966806e+03 -1.48312097e+04 -1.75228081e+04  1.97340253e+04
 -1.39603493e+04  2.02132876e+04  1.32668694e+04 -1.38560090e+04
 -1.22573708e+04 -1.02523777e+04 -2.56846924e+02 -1.07225351e+04
  5.87962053e+04 -7.34303982e+03 -8.86864635e+03 -6.39957708e+03
 -3.46123233e+03  1.02568415e+04 -6.01980298e+03  5.87552012e+03
 -2.02455898e+04  1.69789996e+04  4.17621593e+03 -1.16137505e+03
  8.91726890e+04  5.20942681e+04  6.95288117e+04  8.40855242e+04
 -3.87396782e+05  1.04411071e+04  5.72981662e-11  8.20743825e+04
  2.78769538e+03  9.64918670e+03 -2.25384199e+03 -6.78502939e+03
 -3.39801070e+03  9.16598516e+02  1.15088551e+04  2.52552175e+02
 -2.66933361e+04  3.07383055e+03 -3.08915910e+03  6.16121745e+03
  7.86944149e+03 -6.87986363e+03 -7.96266226e+03  9.52870632e+02
 -6.89272446e+03  1.03412726e+04  1.04411071e+04 -2.71029421e-10
 -2.41974023e+04  1.00923491e+05 -8.73114914e-11 -4.44619226e+04
 -2.83169412e+04 -4.82259320e+04  4.42787075e+04  1.50780139e+04
 -4.91127139e-11 -1.73807922e+04  1.55860012e+04  1.60071068e-10
 -1.20869927e+04 -1.62988217e+03 -1.11527163e+04 -1.32934930e+03
  6.37484820e+02  2.14639078e+04 -4.96450467e+03  2.75979978e+03
 -6.23923142e+03 -7.41738689e+02 -6.79712553e+03  4.44042653e+03
 -1.22587698e+02 -3.57136075e+03 -2.91038305e-11  1.84543894e+04
  3.41261026e+03  2.95365277e+03  9.61294113e+03 -3.94186793e+04
 -2.38651107e+02 -2.28259715e+04  1.12424690e+04  5.76046745e+03
  1.18170577e+04  5.28036172e+03 -8.09447015e+03 -1.72120237e+03
  6.69586750e+01  9.74871385e+03  3.02021730e+04 -3.25630498e+03
 -1.33329273e+04 -1.36129408e+04 -3.79430535e+02  4.73706993e+03
 -3.67966878e+03  2.18278728e-11 -6.77970613e+02 -3.52973826e+03
  3.93779498e+03  5.28203572e+03 -9.38269924e+02  1.54741327e+04
 -2.02259552e+04  9.19325246e+03 -6.45608264e+03 -4.35283916e+03
  1.61566934e+03 -6.97687199e+03 -7.49500417e+03  1.79957649e+04
 -3.52388876e+03 -3.02097018e+03  1.64306884e+04 -6.39050110e+03
 -7.01921714e+03 -2.12396382e+03  1.22733121e+03  4.22525966e+03
 -6.55146150e+03 -7.84332606e+02  4.00716706e+03  1.44383756e+04
 -2.56964839e+03  3.55272541e+03 -1.01326422e+04  1.83018890e+02
 -5.47182936e+03 -2.54992662e+03  3.53451544e+03 -7.06899786e+03
 -4.81003388e+02 -2.05929204e+04  2.71583329e+04  3.06456091e+03
 -1.81681652e+03  1.95451680e+02 -7.27595761e-12 -1.44319606e+03
  2.51122712e+03 -2.51122712e+03 -4.86376508e+03 -3.73114385e+03
 -2.09102341e+03  1.79957649e+04 -7.30983257e+03  1.82940510e+04
 -4.18742076e+03 -6.74655347e+03 -7.36007677e+03  6.34431487e+03
  1.50638774e+03  6.60888036e+03  1.21335622e+04 -1.45356594e+03
 -4.41065865e+04  1.89670072e+04 -1.61750085e+04 -9.77192135e+02
 -1.95276461e+02  5.58049231e+03  9.57205468e+03  2.19493009e+03
 -1.56181606e+03  6.72133750e+02  8.89682307e+02  8.90935890e+04
 -1.35072766e+04 -1.24469053e+04 -5.46726235e+04 -8.46678373e+03
 -7.79199772e+04  1.51899919e+04  1.77120858e+04  3.01776577e+04
  1.48402418e+04  2.95756102e+03 -6.17907404e+03  3.22151303e+03
 -8.32588541e+03 -9.80135983e+03  3.52859943e+04 -3.45994850e+03
 -1.31231764e+04 -1.26878476e+04  7.40176265e+03  1.64744828e+04
 -1.17640220e+04 -1.15070943e+04 -4.13106965e+03  1.74893954e+04
 -1.52590038e+03  2.01320620e+03 -2.33853725e+03]
Intercept:  752515.0700980495

#### Evaluate with 3 metrics

In [15]:
y_pred = reg.predict(X_test)

# r^2 score
from sklearn.metrics import r2_score
print('r^2 Score: ', r2_score(y_test,y_pred))

# MAE
from sklearn.metrics import mean_absolute_error
print('MAE : ',mean_absolute_error(y_test, y_pred))

# RMSE
from sklearn.metrics import mean_squared_error
print('RMSE : ',mean_squared_error(y_test, y_pred, squared=False))

r^2 Score:  0.7133951119985935
MAE :  20280.566852174532
RMSE :  43523.98323232034

#### Conclusion

- nilai r^2 dari model terhadap data adalah sebesar 0.71 atau 71% yang menandakan bahwa pemodelan yang dibuat mirip sebesar 71% terhadap data yang ada dan dapat dikatakan baik. 
- Nilai MAE menyatakan besaran error rata-rata pada model prediksi, dimana MAE yang didapatkan adalah sebesar 20280.566852174532 yang berarti kemungkinan rata-rata error pada mooel dari data aslinya adalah +20280.566852174532 dan -20280.566852174532
- RMSE adalah skor kuadrat yang mengkur besar error rata-rata, dalam kasus ini didapatkan RMSE sebesar +43523.98323232034 dan -43523.98323232034 dari data aslinya.